# Generated by Django 3.0.3 on 2020-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='LastName', max_length=100),
        ),
    ]
