# Generated by Django 3.0.3 on 2020-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
